accounts/urls.py
from django.urls import path
from accounts import views
import accounts

app_name = 'accounts'
urlpatterns = [
    path('cash-flow/', views.cash_flow, name='cash_flow'),
    path('statement/', views.statement, name='statement'),
    path('credit-page/', views.credit_page, name='credit_page'),
    path('add-credit/', views.add_credit, name='add_credit'),
    path('credit-transfer-page/', views.credit_transfer_page, name='credit_transfer_page'),
    path('transfer-credit/', views.transfer_credit, name='transfer_credit'),
    path('withdraw-credit-page/', views.withdraw_credit_page, name='withdraw_credit_page'),
    path('withdraw-credit/', views.withdraw_credit, name='withdraw_credit'),


    #Supplier Payment
    path('supplier-payment/', views.supplier_payment, name='supplier_payment'),
    path('add-supplier-payment/', views.add_supplier_payment, name='add_supplier_payment'),


    #Loss profit views-url
    path('loss-profit/', views.loss_profit, name='loss_profit'),
    
]

pos/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth.views import (
    PasswordResetView, 
    PasswordResetConfirmView, 
    PasswordResetDoneView, 
    PasswordResetCompleteView
)
from django.contrib import admin

admin.site.site_header = 'XoftNology'                      # default: "Django Administration"
admin.site.index_title = 'XoftNology Dashboard'          # default: "Site administration"
admin.site.site_title = 'Admin' # default: "Django site admin"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='products')),
    path('', include('customers.urls', namespace='customers')),
    path('', include('suppliers.urls', namespace='suppliers')),
    path('', include('sales.urls', namespace='sales')),
    path('', include('inventories.urls', namespace='inventories')),
    path('', include('expenses.urls', namespace='expenses')),
    path('', include('purchases.urls', namespace='purchases')),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('users.urls',  namespace='users')),
    path('', include('app_settings.urls', namespace='app_settings')),

    path('password-reset/', PasswordResetView.as_view(
        template_name='users/password_reset/password_reset.html'), 
        name='password_reset'), 

    path('password_reset/done', PasswordResetDoneView.as_view(
        template_name='users/password_reset/password_reset_done.html'), 
        name='password_reset_done'),  

    path('password_reset_confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset/password_reset_confirm.html'), 
        name='password_reset_confirm'),

    path('password_reset/complete/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset/password_reset_complete.html'),
        name='password_reset_complete'),



]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/forms.py
from django import forms
from django.db import models

from accounts.models import Credit, CreditTransfer, SupplierPayment, Withdraw

class CreditModelForm(forms.ModelForm):
    class Meta:
        model = Credit
        exclude = ('added_by', 'edited_by',)


class CreditTransferModelForm(forms.ModelForm):
    class Meta:
        model = CreditTransfer
        exclude = ('added_by', 'edited_by',)

class WithdrawModelForm(forms.ModelForm):
    class Meta:
        model = Withdraw
        exclude = ('added_by', 'edited_by',)

class SupplierPaymentForm(forms.ModelForm):
    class Meta:
        model = SupplierPayment
        exclude = ['added_by', 'edited_by', 'supplier']

accounts/views.py
from typing import Generic
from django.db import transaction
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

import datetime
import ast
import json

from accounts.forms import (
    CreditModelForm,
    CreditTransferModelForm,
    WithdrawModelForm,
    SupplierPaymentForm
)
from accounts.models import CashFlow, Credit, CreditMethod, CreditTransfer, Statement, SupplierPayment, Withdraw

from sales.models import Sale
from products.models import Product
from expenses.models import Expense


# class CashFlowList(Generic.ListView):
# 	objects = CashFlow.objects.all()
# 	for item in objects:
# 		item.description = eval(str(item.description)
		
# 	queryset = Post.objects.filter(status=1).order_by('-created_on')
# 	template_name = 'index.html'
# 	paginate_by = 3

# Create your views here.
def cash_flow(request):

	page = request.GET.get('page', 1)
	objects = CashFlow.objects.all().order_by("-created")
	

	for item in objects:
		item.description = eval(str(item.description))

	paginator = Paginator(objects, 10)

	try:
		objects = paginator.page(page)
	except PageNotAnInteger:
		objects = paginator.page(1)
	except EmptyPage:
		objects = paginator.page(paginator.num_pages)


	context = {
        'title': 'Transaction History',
        'objects': objects,
    }

    # objects = CashFlow.objects.all()
    # for item in objects:
    #     item.description = eval(str(item.description))

    # context = {
    #     'title': 'Transaction History',
    #     'objects': objects,
    # }
	return render(request, 'accounts/cash-flow.html', context)


def statement(request):
    statements = Statement.objects.all()
    cash = CreditMethod.objects.get(method='cash')
    mobile_banking = CreditMethod.objects.get(method='mobile banking')
    bank = CreditMethod.objects.get(method='bank')

    context = {
        'title': 'Accounts',
        'cash': cash,
        'mobile_banking': mobile_banking,
        'bank': bank,
        'statements': statements,
    }

    return render(request, 'accounts/statement.html', context)


def credit_page(request):
    credit = Credit.objects.all()
    creditForm = CreditModelForm()
    credit_method = CreditMethod.objects.all()

    total_credit = sum(item.total_amount for item in credit_method)

    context = {
        'title': 'Credit',
        'credit_method': credit_method,
        'credits': credit,
        'creditForm': creditForm,
        'total_credit': total_credit,
    }
    return render(request, 'accounts/credit-page.html', context)


def add_credit(request):
    if request.method == 'POST':
        with transaction.atomic():
            form = CreditModelForm(request.POST)
            if form.is_valid():
                credited_amount = request.POST.get('amount')
                payment_method = CreditMethod.objects.get(
                    id=request.POST.get('credit_method'))
                instance = form.save(commit=False)
                print('id.... ', instance.id)
                instance.added_by = request.user
                instance.save()  # Here is a signal

                messages.success(
                    request, f'{credited_amount} Tk. has been successfully credited to {payment_method.method.upper()}.')
                return redirect(request.META['HTTP_REFERER'])


def credit_transfer_page(request):
    credit_transfer = CreditTransfer.objects.all()
    creditTransferForm = CreditTransferModelForm()

    context = {
        'title': 'Credit Transfer',
        'credit_transfer': credit_transfer,
        'creditTransferForm': creditTransferForm,
    }
    return render(request, 'accounts/credit-transfer-page.html', context)


def transfer_credit(request):
    if request.method == 'POST':
        with transaction.atomic():
            form = CreditTransferModelForm(request.POST)
            transfer_from = request.POST.get('transfer_from')
            transfer_to = request.POST.get('transfer_to')
            transfer_amount = request.POST.get('amount')
            transfer_from_credit_method = CreditMethod.objects.get(
                method=transfer_from)

            if transfer_from_credit_method.total_amount < int(transfer_amount):
                messages.error(
                    request, f'Oops! There is not enough balance in {transfer_from.upper()} to transfer.')
                return redirect(request.META['HTTP_REFERER'])
            elif transfer_to == transfer_from:
                messages.error(
                    request, f'Oops! You cannot transfer credit from {transfer_from.upper()} to {transfer_from_credit_method.method.upper()}.')
                return redirect(request.META['HTTP_REFERER'])
            else:
                if form.is_valid():
                    instance = form.save(commit=False)
                    instance.added_by = request.user
                    instance.save()

                    messages.success(
                        request, f'Credit has been transferred successfully from {transfer_from.upper()} to {transfer_to.upper()}.')
                    return redirect(request.META['HTTP_REFERER'])


def withdraw_credit_page(request):
    withdraw_credit = Withdraw.objects.all()
    withdrawForm = WithdrawModelForm()

    context = {
        'title': 'Withdraw Credit',
        'withdraw_credit': withdraw_credit,
        'withdrawForm': withdrawForm,
    }
    return render(request, 'accounts/withdraw-credit-page.html', context)


def withdraw_credit(request):
    if request.method == 'POST':
        with transaction.atomic():
            form = WithdrawModelForm(request.POST)
            withdraw_from = request.POST.get('withdraw_from')
            withdraw_amount = request.POST.get('amount')
            withdraw_from_credit_method = CreditMethod.objects.get(
                method=withdraw_from)

            if withdraw_from_credit_method.total_amount < int(withdraw_amount):
                messages.error(
                    request, f'Oops! There is not enough balance in {withdraw_from.upper()} to withdraw.')
                return redirect(request.META['HTTP_REFERER'])
            else:
                if form.is_valid():
                    instance = form.save(commit=False)
                    instance.added_by = request.user
                    instance.save()

                    messages.success(
                        request, f'{withdraw_amount} Tk has been withdrawn successfully from {withdraw_from.upper()}.')
                    return redirect(request.META['HTTP_REFERER'])


# Supplier payment page
def supplier_payment(request):
    supplier_payments = SupplierPayment.objects.all().order_by('-created')
    form = SupplierPaymentForm()
    context = {
        'title': 'Supplier Payments',
        'supplier_payments': supplier_payments,
        'form': form,
        'title': 'Supplier Payment'
    }
    return render(request, 'accounts/supplier_payment.html', context)


# Creating Supplier payment
def add_supplier_payment(request):
    if request.method == 'POST':
        with transaction.atomic():
            form = SupplierPaymentForm(request.POST)
            if form.is_valid():
                return _extracted_from_add_supplier_payment(form, request)


def _extracted_from_add_supplier_payment(form, request):
    purchase_invoice = form.cleaned_data.get('purchase_invoice')
    payment_amount = form.cleaned_data.get('amount')
    total_due_amount = purchase_invoice.get_total_due_amount
    if purchase_invoice.is_complete:
        messages.error(
            request, 'You cannot pay because you do not have due for this purchase')
        return redirect(request.META['HTTP_REFERER'])

    instance = form.save(commit=False)
    if total_due_amount < payment_amount:
        instance.amount = total_due_amount

    supplier = purchase_invoice.supplier
    instance.added_by = request.user
    instance.supplier = supplier
    instance.save()
    messages.success(request, 'Payment successfully added')
    return redirect(request.META['HTTP_REFERER'])


# Making Yearly Report for selling
def loss_profit(request):
    if request.method == 'POST':
        '''
        Getting current year's  starting date
        and ending date from user
        '''
        starting_year_date = request.POST.get('min')
        ending_year_date = request.POST.get('max')
        date_from_user = True
        '''
        Getting current year's  all Sale objects
        and getting total from it
        '''
        sales = Sale.objects.filter(
            delivery_date__gte=starting_year_date,
            delivery_date__lte=ending_year_date,
            is_complete=True
        )
        subtotal = sum(sale.get_sub_total for sale in sales)
        total_sold_amount_with_discount = sum(
            sale.get_total_sold_price for sale in sales)
        total_payable = sum(sale.get_total_payable for sale in sales)
        total_other_fee = sum(sale.other_fee for sale in sales)
        total_discount = sum(sale.get_discount for sale in sales)

        '''
        Getting current year's  all Product objects
        and getting total from it
        '''
        products = Product.objects.filter(
            created__gte=starting_year_date,
            created__lte=ending_year_date
        )
        total_cost_amount_on_product = sum(
            product.cost_price for product in products)

        '''
        Getting current year's  all Expense objects
        and getting total from it
        '''
        expenses = Expense.objects.filter(
            created__gte=starting_year_date,
            created__lte=ending_year_date,
        )
        total_expense = sum(expense.amount for expense in expenses)

        '''
        Getting current year's  Gross Profit
        '''
        gross_profit = total_sold_amount_with_discount - total_cost_amount_on_product

        '''
        Getting current year's  Net Profit
        '''

accounts/templates/accounts/add-credit-modal.html
{% load crispy_forms_tags %}
<div id="add-credit-modal-show" style="display: none;">
    <form action="{% url 'accounts:add_credit' %}" method="POST">
        {% csrf_token %}
        {{creditForm|crispy}}
        <button type="submit" class="btn btn-info btn-lg btn-block float-right">Submit</button>
    </form>
</div>

accounts/templates/accounts/add-supplier-payment-modal.html
{% load crispy_forms_tags %}
<div id="add-supplier-payment-modal-show" style="display: none;">
    <form action="{% url 'accounts:add_supplier_payment' %}" method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-info btn-lg btn-block float-right">Submit</button>
    </form>
</div>

accounts/templates/accounts/cash-flow.html
{% extends 'base.html' %}
{% load static %}
{% block datatable_js_script %} 
<script src="{% static 'js/cash-flow-datatable.js' %}"></script>
{% endblock datatable_js_script %}
{% block content %}
<div class="card mt-5">
    <div class="p-4">
        <div class="row">
            <div class="col-sm-6 ">
                <span class="display-4">Transaction History</span>
            </div>
            <div class="col-sm-6 printbar  text-right">
                <!-- Here shows pdf, csv, print, copy, excel button by plugins  -->
            </div>
        </div>
    </div>
    <div class="card-body">
        <div class="row justify-content-center">
            <div class="form-group col-3">
                <label>Minimum date:</label>
    
                <div class="input-group">
                  <div class="input-group-prepend">
                    <span class="input-group-text"><i class="far fa-calendar-alt"></i></span>
                  </div>
                  <input type="text" id="min" name="min" class="form-control">
                </div>
                <!-- /.input group -->
            </div>

            <div class="form-group col-3">
                <label>Maximum date:</label>

                <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="far fa-calendar-alt"></i></span>
                </div>
                <input type="text" id="max" name="max" class="form-control">
                </div>
                <!-- /.input group -->
            </div>
        </div>


        <table id="datatable" class="table table-striped table-bordered" style="width:100%">
            <thead>
                <tr>
                    <th>Date</th>
                    <th class="text-center">Id</th>
                    <th>Credit Method</th>
                    <th>Description</th>
                    <th>Credit</th>
                    <th>Debit</th>
                    <th>Current Credit</th>
                </tr>
            </thead>
            <tbody>
                {% for item in objects %}
                    <tr>
                        <td>  {{item.created|date:"M d, Y"}} </td>
                        <td class="text-center"> {{item.id}} </td>
                        <td>  {{ item.credit_method }} </td>
                        <td> 
                            {% for key, value in item.description.items %}
                                {% if value %}
                                    <div>
                                        <strong>{{ key|upper }}:</strong>  {{ value|title }}
                                    </div>
                                {% endif %}
                            {% endfor %}
                        </td>
                        {% if item.is_debit == False %}
                            <td>  {{ item.amount }} </td>
                        {% else %}
                            <td class="text-center">-</td>
                        {% endif %}
                        {% if item.is_debit %}
                            <td>  {{ item.amount }} </td>
                        {% else %}
                            <td class="text-center">-</td>  
                        {% endif %}
                        <!-- <td>  {{ item.delivery_date|date:"M d, Y" }} </td> -->
                        <td>{{ item.remaining_credit }}</td>
                    </tr>
                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <th>Date</th>
                    <th class="text-center">Id</th>
                    <th>Credit Method</th>
                    <th>Description</th>
                    <th>Credit</th>
                    <th>Debit</th>
                    <th>Current Credit</th>
                </tr>
            </tfoot>
        </table>
		<nav aria-label="Page navigation example">
			{% if objects.has_other_pages %}
				<ul class="pagination justify-content-center">
				{% if objects.has_previous %}
					<li class="page-item">
						<a class="page-link" href="?page={{ objects.previous_page_number }}" tabindex="-1">Previous</a>
					</li>
				{% else %}
					<li class="page-item disabled">
						<a class="page-link" href="#" tabindex="-1">Previous</a>
					</li>
				{% endif %}
				{% for i in objects.paginator.page_range %}
					{% if objects.number == i %}
						<li class="page-item active"><a class="page-link" href="#">{{ i }}</a></li>
					{% else %}
						<li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
					{% endif %}
				{% endfor %}
				{% if objects.has_next %}
				<li class="page-item">
					<a class="page-link" href="?page={{ objects.next_page_number }}">Next</a>
				</li>
				{% else %}
				<li class="page-item disabled">
					<a class="page-link" href="?page={{ objects.next_page_number }}">Next</a>
				</li>
				{% endif %}
		
		
				</ul>
			{% endif %}
		</nav>
    </div>
</div>


{% endblock %}

accounts/templates/accounts/credit-page.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block modal_scripts %}
<script src="{% static 'js/accounts-modals.js' %}"></script>
{% endblock modal_scripts %}
{% block content %}
<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col-sm-6 ">
                <span class="display-4">Credit History</span>
            </div>
            
            <div class="col-sm-6 printbar  text-right">
                <!-- Here shows pdf, csv, print, copy, excel button by plugins  -->
            </div>
        </div>

        <div class="col d-flex justify-content-end">
            <button id="add-credit" class="btn btn-info">
                <i class="fas fa-plus"></i>
                Add Credit
            </button>
        </div>
    <div class="card-body">
        <table id="datatable" class="table table-striped table-bordered" style="width:100%">
            <thead>
                <tr>
                    <th>Transaction Id</th>
                    <th>Created at</th>
                    <th>Title</th>
                    <th>Description</th>
                    <th>Credit Method</th>
                    <th>Updated at</th>
                    <th>Added By</th>
                    <th>Amount</th>>
                </tr>
            </thead>
            <tbody>
                {% for item in credits %}
                    <tr>
                        <td>  #00{{ item.id }} </td>
                        <td>  {{ item.created }} </td>
                        <td>  {{ item.title }} </td>
                        <td>  {{ item.description }} </td>
                        <td>  {{ item.credit_method.method|upper }}</td>
                        <td>  {{ item.edited }} </td>
                        <td>  {{ item.added_by }} </td>
                        <td>  {{ item.amount|intcomma }} </td>
                        
                    </tr>

                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <th>Transaction Id</th>
                    <th>Created at</th>
                    <th>Title</th>
                    <th>Description</th>
                    <th>Credit Method</th>
                    <th>Updated at</th>
                    <th>Added By</th>
                    <th>Amount</th>>
                </tr>
            </tfoot>
        </table>
    </div>
    {% include 'accounts/add-credit-modal.html' %}
</div>

{% endblock %}

accounts/templates/accounts/credit-transfer-page.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block modal_scripts %}
<script src="{% static 'js/accounts-modals.js' %}"></script>
{% endblock modal_scripts %}
{% block content %}
<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col-sm-6 ">
                <span class="display-4">Credit Transfer History</span>
            </div>
            
            <div class="col-sm-6 printbar  text-right">
                <!-- Here shows pdf, csv, print, copy, excel button by plugins  -->
            </div>
        </div>

        <div class="col d-flex justify-content-end">
            <button id="transfer-credit" class="btn btn-info">
                <i class="fas fa-plus"></i>
                Transfer Credit
            </button>
        </div>
    <div class="card-body">
        <table id="datatable" class="table table-striped table-bordered" style="width:100%">
            <thead>
                <tr>
                    <th>Transaction Id</th>
                    <th>Created at</th>
                    <th>Title</th>
                    <th>Description</th>
                    <th>Transfer From</th>
                    <th>Transfer To</th>
                    <th>Amount</th>
                    <th>Updated at</th>
                    <th>Added By</th>
                    <th>Edited By</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for item in credit_transfer %}
                    <tr>
                        <td>  #00{{ item.id }} </td>
                        <td>  {{ item.created }} </td>
                        <td>  {{ item.title }} </td>
                        <td>  {{ item.description }} </td>
                        <td>  {{ item.transfer_from|upper }}</td>
                        <td>  {{ item.transfer_to|upper }}</td>
                        <td>  {{ item.amount|intcomma }} </td>
                        <td>  {{ item.edited }} </td>
                        <td>  {{ item.added_by }} </td>
                        <td>  {{ item.edited_by }} </td>
                        <td>
                            <a href="">
                                <i class="fas fa-edit"></i>
                            </a>
                                
                            
                            <span class="js-delete-customer" data-customer_id="{{ customer.id }}">
                                <i class="fas fa-trash"></i>
                            </span>
                        </td>
                        
                    </tr>

                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <th>Transaction Id</th>
                    <th>Created at</th>
                    <th>Title</th>
                    <th>Description</th>
                    <th>Transfer From</th>
                    <th>Transfer To</th>
                    <th>Amount</th>
                    <th>Updated at</th>
                    <th>Added By</th>
                    <th>Edited By</th>
                    <th>Action</th>
                </tr>
            </tfoot>
        </table>
    </div>
    {% include 'accounts/transfer-credit-modal.html' %}
</div>

{% endblock %}

accounts/templates/accounts/statement.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load humanize %}
{% block content %}
<div class="card">
    
    <div class="card-body">
        <div class="row">
            <div class="col-lg-4 col-6">
              <!-- small box -->
              <div class="small-box bg-info">
                <div class="inner">
                  <h3>{{ cash.total_amount }} BDT</h3>
        
                  <p>CASH</p>
                </div>
                <div class="icon">
                  <i class="ion ion-bag"></i>
                </div>
              </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-4 col-6">
              <!-- small box -->
              <div class="small-box bg-info">
                <div class="inner">
                  <h3>{{ bank.total_amount }} BDT</h3>
        
                  <p>BANK</p>
                </div>
                <div class="icon">
                  <i class="ion ion-stats-bars"></i>
                </div>
              </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-4 col-6">
              <!-- small box -->
              <div class="small-box bg-info">
                <div class="inner">
                  <h3>{{ mobile_banking.total_amount }} BDT</h3>
                  
        
                  <p>MOBILE BANKING</p>
                </div>
                <div class="icon">
                  <i class="ion ion-pie-graph"></i>
                </div>
              </div>
            </div>
            <!-- ./col -->
        </div>
    </div>


    <div class="p-4">
        <div class="row">
            <div class="col-sm-6 ">
                <span class="display-4">Statement</span>
            </div>
            
            <div class="col-sm-6 printbar  text-right">
                <!-- Here shows pdf, csv, print, copy, excel button by plugins  -->
            </div>
        </div>
    </div>
    <div class="card-body">
        <table id="id_statement" class="table table-striped table-bordered" style="width:100%">
            <thead>
                <tr>
                    <th>Transaction Id</th>
                    <th>Created at</th>
                    <th>Title</th>
                    <th>Description</th>
                    <th>Adding Credit To</th>
                    <th>Withdraw From</th>
                    <th>Transfer From</th>
                    <th>Transfer To</th>
                    <th>Amount</th>
                </tr>
            </thead>
            <tbody>
                {% for item in statements %}
                    <tr>
                        <td>  #00{{ item.statement_id }} </td>
                        <td>  {{ item.date }} </td>
                        <td>  {{ item.title }} </td>
                        <td>  {{ item.description }} </td>
                        <td>  {{ item.credit_to }} </td>
                        <td>  {{ item.withdraw_from }} </td>
                        <td>  {{ item.transfer_from|upper }}</td>
                        <td>  {{ item.transfer_to|upper }}</td>
                        <td>  {{ item.amount|intcomma }} </td>
                    </tr>

                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <th>Transaction Id</th>
                    <th>Created at</th>
                    <th>Title</th>
                    <th>Description</th>
                    <th>Adding Credit To</th>
                    <th>Withdraw From</th>
                    <th>Transfer From</th>
                    <th>Transfer To</th>
                    <th>Amount</th>
                </tr>
            </tfoot>
        </table>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/transfer-credit-modal.html
{% load crispy_forms_tags %}
<div id="transfer-credit-modal-show" style="display: none;">
    <form action="{% url 'accounts:transfer_credit' %}" method="POST">
        {% csrf_token %}
        {{creditTransferForm|crispy}}
        <button type="submit" class="btn btn-info btn-lg btn-block float-right">Submit</button>
    </form>
</div>

accounts/templates/accounts/withdraw-credit-modal.html
{% load crispy_forms_tags %}
<div id="withdraw-modal-show" style="display: none;">
    <form action="{% url 'accounts:withdraw_credit' %}" method="POST">
        {% csrf_token %}
        {{withdrawForm|crispy}}
        <button type="submit" class="btn btn-info btn-lg btn-block float-right">Submit</button>
    </form>
</div>