pos/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth.views import (
    PasswordResetView, 
    PasswordResetConfirmView, 
    PasswordResetDoneView, 
    PasswordResetCompleteView
)
from django.contrib import admin

admin.site.site_header = 'XoftNology'                      # default: "Django Administration"
admin.site.index_title = 'XoftNology Dashboard'          # default: "Site administration"
admin.site.site_title = 'Admin' # default: "Django site admin"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='products')),
    path('', include('customers.urls', namespace='customers')),
    path('', include('suppliers.urls', namespace='suppliers')),
    path('', include('sales.urls', namespace='sales')),
    path('', include('inventories.urls', namespace='inventories')),
    path('', include('expenses.urls', namespace='expenses')),
    path('', include('purchases.urls', namespace='purchases')),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('users.urls',  namespace='users')),
    path('', include('app_settings.urls', namespace='app_settings')),

    path('password-reset/', PasswordResetView.as_view(
        template_name='users/password_reset/password_reset.html'), 
        name='password_reset'), 

    path('password_reset/done', PasswordResetDoneView.as_view(
        template_name='users/password_reset/password_reset_done.html'), 
        name='password_reset_done'),  

    path('password_reset_confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset/password_reset_confirm.html'), 
        name='password_reset_confirm'),

    path('password_reset/complete/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset/password_reset_complete.html'),
        name='password_reset_complete'),



]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

purchases/urls.py
from django.urls import path
from purchases import views

app_name = 'purchases'
urlpatterns = [
    path('create-purchase/', views.create_purchase, name='create_purchase'),
    # path('update-purchase-invoice/<int:pk>/', views.update_purchase_invoice, name='update_purchase_invoice'),
    path('delete-purchase-invoice/', views.delete_purchase_invoice, name='delete_purchase_invoice'),

    # Purchase return product
    path('delete-purchase-return/', views.delete_purchase_return, name='delete_purchase_return'),
    path('return-purchase-product/', views.return_purchase_product, name='return_purchase_product'),
    
    path('purchase-history/', views.purchase_history, name='purchase_history'),
    path('purchase-invoice-details/<int:pk>/', views.purchase_invoice_details, name='purchase_invoice_details'),
    path('purchase-report/', views.purchase_report, name='purchase_report'),
    

]
# args=[str(self.id)]
# args=[str:pk]

purchases/forms.py
from django import forms
from django.forms import fields

from suppliers.models import Supplier
from purchases.models import Purchase, PurchaseInvoice, ReturnPurchaseProduct
from products.models import Product


class ModelPurchaseForm(forms.ModelForm):
    class Meta:
        model = Purchase
        fields = (
                    'product', 'brand', 'cost_price', 
                    'selling_price', 'qty', 'discount', 
                    'is_discount_in_parcentage', 'purchase_by'
                )
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.render_required_fields = True



class PurchaseInvoiceUpdateForm(forms.ModelForm):
    class Meta:
        model = PurchaseInvoice
        fields = ['is_complete']

class ReturnPurchaseProductForm(forms.ModelForm):
    class Meta:
        model = ReturnPurchaseProduct
        exclude = ['added_by', 'edited_by', 'cost_price',]



class SupplierForm(forms.ModelForm):
    class Meta:
        model = Purchase
        fields = ('supplier',)

class SupplierModelForm(forms.ModelForm):
    class Meta:
        model = Supplier
        exclude = ('added_by', 'updated_by',)

purchases/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.shortcuts import render, redirect
from django.forms.formsets import formset_factory
from django.db import transaction, IntegrityError
from django.contrib import messages


from django.contrib.auth.decorators import login_required, user_passes_test


from purchases.forms import (ModelPurchaseForm, 
                            SupplierForm,
                            PurchaseInvoiceUpdateForm
                        )

from purchases.models import (
                    Purchase, 
                    PurchaseInvoice, 
                    ReturnPurchaseProduct
                )
from purchases.forms import ReturnPurchaseProductForm
from products.models import Product
from products.forms import ProductModelForm
from suppliers.models import Supplier
from suppliers.forms import SupplierModelForm
from accounts.models import CreditMethod, CashFlow, SupplierPayment
from utils.create_cashflow import create_cashflow





@login_required()
@user_passes_test(lambda u: u.is_active or u.is_manager or u.is_owner or u.is_superuser)
def create_purchase(request):
    supplierModelForm = SupplierModelForm()
    productModelForm = ProductModelForm()

    total_order = request.GET.get('order_no')
    if total_order:
        total_order = int(total_order)
        if total_order and total_order > 0:
            formSet = formset_factory(ModelPurchaseForm, extra=total_order)
            
            sForm = SupplierForm()
    else:
        formSet = ''
        sForm = ''



    if request.method == "POST":
        
        formSet = formSet(request.POST)
        sForm = SupplierForm(request.POST)
        
        if formSet.is_valid() and sForm.is_valid():
            supplier = Supplier.objects.get(id=request.POST.get('supplier'))

            # Minus purchase payment from Credit Method.
            payment_method = request.POST.get('payment_method')
            if payment_method != '':
                # payment_method = payment_method.lower()
                # purchase_payment = int(request.POST.get('purchase_payment'))
                # credit_method = CreditMethod.objects.get(method=payment_method)
                # credit_method.total_amount = credit_method.total_amount - purchase_payment
                # credit_method.save()

                                
                purchase_payment = int(request.POST.get('purchase_payment'))
                # creating  Purchase Invoice Table
                PurchaseInvoice.objects.create()
                pur_invoice = PurchaseInvoice.objects.last()
                
            try:
                with transaction.atomic():
                    for form in formSet:
                        data = form.cleaned_data
                        if data:
                            instance = form.save(commit=False)
                            instance.supplier = supplier
                            instance.purchase_invoice = pur_invoice
                            instance.added_by = request.user
                            instance.save()

                            purchase = Purchase.objects.last()
                            product_id = purchase.product.id
                            product = Product.objects.get(id=product_id)
                            product.brand = purchase.brand

                            purchases = Purchase.objects.filter(product=product)
                            total_products = purchases.count()
                            total_product_amount = sum(item.cost_price for item in purchases)
                            total_average_product_price = total_product_amount / total_products

                            product.cost_price = total_average_product_price
                            
                            if purchase.selling_price != 0:
                                product.selling_price = purchase.selling_price


                            product.discount = purchase.discount
                            product.is_discount_in_parcentage = purchase.is_discount_in_parcentage
                            product.purchase_qty = product.purchase_qty + purchase.qty
                            product.save()

                    # updating last created PurchaseInvoice
                    total_purchase_amount = pur_invoice.get_total_purchase_amount
                    if total_purchase_amount != purchase_payment and not total_purchase_amount < purchase_payment:
                        pur_invoice.supplier = supplier
                        pur_invoice.payment_method = payment_method
                        pur_invoice.is_complete = False
                        pur_invoice.save()

                        SupplierPayment.objects.create(
                            purchase_invoice=pur_invoice,
                            payment_method=payment_method,
                            amount=purchase_payment,
                            description='First Payment',
                            added_by=request.user
                        )
                    else:
                        if total_purchase_amount <= purchase_payment:
                            pur_invoice.supplier = supplier
                            pur_invoice.payment_method = payment_method
                            pur_invoice.is_complete = True
                            pur_invoice.save()

                            SupplierPayment.objects.create(
                                purchase_invoice=pur_invoice,
                                payment_method=payment_method,
                                amount=total_purchase_amount,
                                added_by=request.user
                            )

                    messages.success(request, 'Purchase has been successfully Done!')
                    return redirect(request.META['HTTP_REFERER'])

            except Exception as e:
                print(e)
                messages.error(request, e)
                return redirect(request.META['HTTP_REFERER'])


    context = {
        'formSet': formSet,
        'sForm': sForm,
        'form': supplierModelForm,
        'productModelForm': productModelForm,
    }
    return render(request, 'purchases/create_purchase.html', context)


@login_required()
@user_passes_test(lambda u: u.is_active or u.is_manager or u.is_owner or u.is_superuser)
def purchase_history(request):
    invoices = PurchaseInvoice.objects.all()
    context = {
        'invoices': invoices
    }
    return render(request, 'purchases/purchase-history.html', context)

#Updating purchase invoice
# def update_purchase_invoice(request, pk):
#     try:    
#         purchase_invoice= PurchaseInvoice.objects.get(pk=pk)
#         form = PurchaseInvoiceUpdateForm(instance=purchase_invoice)
#         if request.method == 'POST':
#             form = PurchaseInvoiceUpdateForm(request.POST, instance=purchase_invoice)
#             if form.is_valid():
#                 form.save()
#                 messages.success(request, 'Success! Your Purchase has been completed.')
#                 return redirect('purchases:purchase_history')
#         return render(request, 'purchases/purchase-invoice-update-form.html', {'form': form})
#     except:
#         messages.error(request, 'Oops! Your Purchase Invoice is not found.')
#         return redirect('purchases:purchase_history')
    



# Deleting purchase invoice
@login_required()
@user_passes_test(lambda u: u.is_active or u.is_manager or u.is_owner or u.is_superuser)
def delete_purchase_invoice(request):
    if request.is_ajax:
        purchase_id = request.POST.get('purchase_id')
        PurchaseInvoice.objects.get(id=purchase_id).delete() 
        data = True
    else:
        data = False

    return JsonResponse({'data': data})  



@login_required()
@user_passes_test(lambda u: u.is_active or u.is_manager or u.is_owner or u.is_superuser)
def return_purchase_product(request):
    return_purchase_products = ReturnPurchaseProduct.objects.all()
    form = ReturnPurchaseProductForm()
    if request.method == 'POST':
        form = ReturnPurchaseProductForm(request.POST)
        if form.is_valid():
            try:
                with transaction.atomic():
                    purchase_invoice = form.cleaned_data.get('purchase_invoice')
                    product = form.cleaned_data.get('product')
                    return_qty = form.cleaned_data.get('qty')

                    purchase_product = purchase_invoice.purchase_set.get(product=product)

                    #Preventing adding return puchase product from pending Purchase(PurchaseInvoice)
                    if purchase_invoice.is_complete == False:
                        messages.error(request, 'Cannot return Purchase Product because the Purchase is not complete yet')
                        return redirect(request.META['HTTP_REFERER'])

                    if purchase_product.qty < return_qty:
                        messages.error(request, f'Oops! You are returning {return_qty} quantity but purchase quantity is {purchase_product.qty}')
                        return redirect(request.META['HTTP_REFERER'])
                    else:
                        instance = form.save(commit=False)
                        instance.cost_price = purchase_product.cost_price
                        instance.added_by = request.user
                        instance.save()
                        
                        purchase_product.qty = purchase_product.qty - return_qty
                        purchase_product.save()
                    
                    #deleting product from purchase
                    if purchase_product.qty == 0:
                        purchase_product.delete()
                    
                    if purchase_invoice.purchase_set.count() == 0:
                        purchase_invoice.delete()

purchases/templates/purchases/create_purchase.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block modal_scripts %}
<script src="{% static 'js/supplier-modals.js' %}"></script>
{% endblock modal_scripts %}
    
{% block common_scripts %} 
<script src="{% static 'js/purchase-scripts.js' %}"></script>
{% endblock common_scripts %}
<!-- {% block create_product %}
<script src="{% static 'js/create-product.js' %}"></script>
{% endblock create_product %} -->


{% block content %}
    <div class="container">
        {% if not formSet %}
            <form action="" method="GET">
                <div>
                    <div class="justify-content-center row">
                        <div class="title col-sm-5">
                            <h1 class="display-5">How many orders do you want to purchase under one Supplier?</h1>
                        </div>
                    </div>
                    <div class="justify-content-center row">
                        <div class=" col-sm-5 form-group">
                            <label for="order-no">Enter the number:</label>
                            <input type="number" class="form-control" id="order-no" value="" name="order_no" required>
                            <button type="submit" class="btn btn-info btn-info float-right">Send request</button>
                        </div>
                    </div>
                </div>
            </form>
        {% endif %}

        {% if formSet and sForm %}
            <div class="card mb-3">
                <div class="card-body border border-danger">
                <p class="card-text">
                    <strong>Warning!</strong>
                    Before filling Purchase Form, 
                    You have to add Product if the Product does not exist 
                    and you have to add Supplier if the Supplier does not exist.
                </p>
                </div>
            </div>
            <form action="" method="POST">
                {% csrf_token %}
                {{formSet.management_form}}
                <div class="card text-dark bg-light">
                    <div class="row">
                        <div class="col-sm-3">
                            <a class="btn btn-md btn-info text-white float left js-create-product">
                                <i class="fas fa-plus"></i>
                                Add New Product
                            </a>
                        </div>
                        
                        <div class="col-sm-6">
                            <div class="justify-content-center form-group">
                                {{ sForm|crispy }}
                            </div>
                        </div>
                        
                        <div class="col-sm-3">
                            <a id="create-supplier" class="btn btn-md text-white float-right btn-info">
                                <i class="fas fa-plus"></i>
                                Add New Supplier
                            </a>
                        </div>
                        
                    </div>
                </div>
            

                {% for form in formSet %}
                <div class="card text-dark text-dark bg-light">
                    <h3 class="text-center"><span class="badge badge-info">{{ forloop.counter }}</span></h3>
                    <div class="card-body"">
                        <div class="row">
                            <div class="form-group col-sm-3">
                                {{ form.product|as_crispy_field }}
                            </div>
                            <div class="form-group col-sm-3">
                                {{ form.brand|as_crispy_field }}
                            </div>
                            <div class="form-group js-cost-price col-sm-3">
                                {{ form.cost_price|as_crispy_field }}
                            </div>
                            <div class="form-group col-sm-3">
                                {{ form.selling_price|as_crispy_field }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-sm-3 js-product-qty">
                                {{ form.qty|as_crispy_field }}
                            </div>
                            <div class="form-group col-sm-3">
                                {{ form.discount|as_crispy_field }}
                            </div>
                            <div class="form-group col-sm-3">
                                {{ form.is_discount_in_parcentage|as_crispy_field }}
                            </div>
                            <div class="form-group col-sm-3">
                                {{ form.purchase_by|as_crispy_field }}
                            </div>
                        </div>
                    </div>
                </div>
                
                {% endfor %}
                <!-- spinner -->
                <div  class="d-flex justify-content-center">
                    <div id="purchase-sipnner" class="spinner-border d-none  text-info" role="status">
                        <span class="sr-only "></span>
                    </div>
                </div>

                <div id="final-payment">
                    <!-- Here will be added payment  automatically -->
                </div>

                <div id="card-footer" class="card-footer">
                    <div class="row">
                        <div class="col-sm-6">
                            <a  class="btn btn-sm btn-info btn-block float-left text-white" id="js-generate-total-purchase-price">
                                Generate Final Payment
                                <!-- Generate Total Purchase Price -->
                            </a>
                        </div>
                        <div id="purchase-submit-btn" class="col-sm-6">
                            <!-- Submit button will automatically added here -->
                        </div>
                    </div>
                </div>

            </form>
        {% endif %}
    </div>
    {% include 'suppliers/add-supplier-modal.html' %}
    {% include 'products/add-product-modal.html' %}
{% endblock %}

purchases/templates/purchases/delete-purchase-return-modal.html
<div id="delete-purchase-return-show" style="display: none;">
    {% csrf_token %}
    <div class="row text-center">
        <div class="col-6">
            <button id="delete_purchase_return_no" class="ui-button ui-widget ui-corner-all">No</button>
        </div>
        <div class="col-6">
            <button id="delete_purchase_return_yes"  class="ui-button ui-widget ui-corner-all">Yes</button>
        </div>
    </div>
</div>

purchases/templates/purchases/pr-invoice-details.html
{% extends 'base.html' %}
{% block content %}
<div class="wrapper">
  <!-- Main content -->
  <section class="invoice">
    <!-- title row -->
    <div class="row">
      <div class="col-12">
        <h2 class="page-header">
          {{ site_title }}.
          <small class="float-right">Date: {{supplier.created|date:"M d, Y"}} </small>
        </h2>
      </div>
      <!-- /.col -->
    </div>
    <!-- info row -->
    <div class="row invoice-info">
      <div class="col-sm-4 invoice-col">
        From
        <address>
          <strong> {{supplier.supplier.first_name}} {{supplier.supplier.last_name}} </strong><br>
          Address-1: {{supplier.supplier.address1}} <br>
          Address-2: {{supplier.supplier.address2}} <br>
          Phone-1: {{supplier.supplier.phone1}} <br>
          Phone-2: {{supplier.supplier.phone2}} <br>
          Email: {{supplier.supplier.email}}
        </address>
      </div>
      <!-- /.col -->
      <!-- /.col -->
      <div class="col-sm-4 invoice-col">
        <b>Invoice #00{{invoice.id}}</b><br>
        <br>
        <b>Payment Due:</b> {% if invoice.get_total_due_amount %} {{ invoice.get_total_due_amount }} {% endif %}<br>
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->

    <!-- Table row -->
    <div class="row">
      <div class="col-12 table-responsive">
        <table class="table table-striped">
          <thead>
          <tr>
            <th>Product id #</th>
            <th>Product</th>
            <th>Cost Price</th>
            <th>Qty</th>
            <th>Subtotal</th>
          </tr>
          </thead>
          <tbody>
          {% for item in details %}
          <tr>
            <td> {{item.product.id}}  </td>
            <td> {{item.product.name}} </td>
            <td> {{item.cost_price}} </td>
            <td> {{item.qty}} </td>
            <td> {{item.get_total_price}} </td>
          </tr>
         {% endfor %}
          </tbody>
          <tfoot>
            <tr>
                <th></th>
                <th></th>
                <th></th>
                <th>Total</th>
                <th>{{ invoice.get_total_purchase_amount }}</th>
              </tr>
          </tfoot>
        </table>
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </section>
  <!-- /.content -->
</div>
<!-- ./wrapper -->
<!-- Page specific script -->
<script>
  window.addEventListener("load", window.print());
</script>

{% endblock %}

  <!-- <script>
    window.addEventListener("load", window.print());
    // window.onload = function () {
    //     window.print();
    // }
  </script> -->

purchases/templates/purchases/purchase-history.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block purchase_datatable_js %} 
    <script src="{% static 'js/purchase-datatable.js' %}"></script>
{% endblock purchase_datatable_js %}
{% block content %}
<div class="card">
    <div class="">
        <div class="row">
            <div class="col-sm-6 ">
                <span class="display-4">Purchase History</span>
            </div>
            
            <div class="col-sm-6 printbar  text-right">
                <!-- Here shows pdf, csv, print, copy, excel button by plugins  -->
            </div>
        </div>
        <div class="col d-flex justify-content-end">
            <a href="{% url 'purchases:create_purchase' %}" class="btn btn-md btn-info">
                <i class="fas fa-plus"></i>
                Create Purchase
            </a>
        </div>
    </div>
    <div class="card-body">
        <div class="row justify-content-center">
            <div class="form-group col-3">
                <label>Minimum date:</label>
    
                <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="far fa-calendar-alt"></i></span>
                </div>
                <input type="text" id="min" name="min" class="form-control">
                </div>
               
            </div>

            <div class="form-group col-3">
                <label>Maximum date:</label>

                <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="far fa-calendar-alt"></i></span>
                </div>
                <input type="text" id="max" name="max" class="form-control">
                </div>
                
            </div>
        </div>
        <table id="datatable" class="table table-striped table-bordered" style="width:100%">
            <thead>
                <tr>
                    <th>Invoice Id</th>
                    <th>Purchase Date</th>
                    <th>Supplier Name</th>
                    <th>Phone-1</th>
                    <th>Phone-2</th>
                    <th>Email</th>
                    <th>Address</th>
                    <th>Added By</th>
                    <th>Status</th>
                    <th>Total Purchase Price</th>
                    <th>Total Qty</th>
                </tr>
            </thead>
            <tbody>
                {% for item in invoices %}
                    <tr>
                        
                        <td>  
                            <a href="{% url 'purchases:purchase_invoice_details' item.id %}">{{ item.id }}</a> 
                        </td>
                        <td>  {{ item.created|date:"M d, Y" }} </td>
                        <td>  {{ item.get_supplier}} </td>
                        <td>  {{ item.get_supplier_phone1 }} </td>
                        <td>  {{ item.get_supplier_phone2 }} </td>
                        <td>  {{ item.get_supplier_email }} </td>
                        <td>  {{ item.get_supplier_address1 }} </td>
                        <td>  {{ item.get_sales_man }} </td>
                        {% if item.is_complete %}
                            <td><span class="badge badge-success">Done</span></td>
                        {% else %}
                            <td><span class="badge badge-warning">Pending</span></td>
                        {% endif %}
                        <td>  {{ item.get_total_purchase_amount }} </td>
                        <td>  {{ item.get_total_qty }} </td>
                    </tr>

                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <th>Invoice Id</th>
                    <th>Purchase Date</th>
                    <th>Supplier Name</th>
                    <th>Phone-1</th>
                    <th>Phone-2</th>
                    <th>Email</th>
                    <th>Address</th>
                    <th>Added By</th>
                    <th>Status</th>
                    <th>Total Purchase Price</th>
                    <th>Total Qty</th>
                </tr>
            </tfoot>
        </table>
    </div>
    {% include 'purchases/purchase-delete-modal.html' %}
</div>

{% endblock %}

purchases/templates/purchases/purchase-report.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block purchase_report_datatable_js %} 
    <script src="{% static 'js/purchase-report-datatable.js' %}"></script>
{% endblock purchase_report_datatable_js %}
{% block content %}
<div class="card">
    <div class="p-4">
        <div class="row">
            <div class="col-sm-6 ">
                <span class="display-4">Purchase Report</span>
            </div>
            
            <div class="col-sm-6 printbar  text-right">
                <!-- Here shows pdf, csv, print, copy, excel button by plugins  -->
            </div>
        </div>
    </div>
    <div class="card-body">
        <div class="row justify-content-center">
            <div class="form-group col-3">
                <label>Minimum date:</label>
    
                <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="far fa-calendar-alt"></i></span>
                </div>
                <input type="text" id="min" name="min" class="form-control">
                </div>
               
            </div>

            <div class="form-group col-3">
                <label>Maximum date:</label>

                <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="far fa-calendar-alt"></i></span>
                </div>
                <input type="text" id="max" name="max" class="form-control">
                </div>
                
            </div>
        </div>
        <table id="datatable" class="table table-striped table-bordered" style="width:100%">
            <thead>
                <tr>
                    <th>Invoice Id</th>
                    <th>Purchase Date</th>
                    <th>Supplier Name</th>
                    <th>Phone-1</th>
                    <th>Phone-2</th>
                    <th>Email</th>
                    <th>Address</th>
                    <th>Total Purchase Price</th>
                    <th>Total Qty</th>
                    <th>Added By</th>
                </tr>
            </thead>
            <tbody>
                {% for item in invoices %}
                    <tr>
                        
                        <td>  
                            <a href="{% url 'purchases:purchase_invoice_details' item.id %}">{{ item.id }}</a> 
                        </td>
                        <td>  {{ item.created|date:"M d, Y" }} </td>
                        <td>  {{ item.get_supplier}} </td>
                        <td>  {{ item.get_supplier_phone1 }} </td>
                        <td>  {{ item.get_supplier_phone2 }} </td>
                        <td>  {{ item.get_supplier_email }} </td>
                        <td>  {{ item.get_supplier_address1 }} </td>
                        <td>  {{ item.get_total_price }} </td>
                        <td>  {{ item.get_total_qty }} </td>
                        <td>  {{ item.get_sales_man }} </td>
                        
                    </tr>

                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <th>Invoice Id</th>
                    <th>Purchase Date</th>
                    <th>Supplier Name</th>
                    <th>Phone-1</th>
                    <th>Phone-2</th>
                    <th>Email</th>
                    <th>Address</th>
                    <th>Total Purchase Price</th>
                    <th>Total Qty</th>
                    <th>Added By</th>
                </tr>
            </tfoot>
        </table>
    </div>
</div>

{% endblock %}