pos/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth.views import (
    PasswordResetView, 
    PasswordResetConfirmView, 
    PasswordResetDoneView, 
    PasswordResetCompleteView
)
from django.contrib import admin

admin.site.site_header = 'XoftNology'                      # default: "Django Administration"
admin.site.index_title = 'XoftNology Dashboard'          # default: "Site administration"
admin.site.site_title = 'Admin' # default: "Django site admin"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='products')),
    path('', include('customers.urls', namespace='customers')),
    path('', include('suppliers.urls', namespace='suppliers')),
    path('', include('sales.urls', namespace='sales')),
    path('', include('inventories.urls', namespace='inventories')),
    path('', include('expenses.urls', namespace='expenses')),
    path('', include('purchases.urls', namespace='purchases')),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('users.urls',  namespace='users')),
    path('', include('app_settings.urls', namespace='app_settings')),

    path('password-reset/', PasswordResetView.as_view(
        template_name='users/password_reset/password_reset.html'), 
        name='password_reset'), 

    path('password_reset/done', PasswordResetDoneView.as_view(
        template_name='users/password_reset/password_reset_done.html'), 
        name='password_reset_done'),  

    path('password_reset_confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset/password_reset_confirm.html'), 
        name='password_reset_confirm'),

    path('password_reset/complete/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset/password_reset_complete.html'),
        name='password_reset_complete'),



]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from users import views

app_name = 'users'
urlpatterns = [
    path('user/', views.user, name='user'),
    path('update-user/<int:pk>/', views.update_user, name='update_user'),
    path('create-user/', views.create_user, name='create_user'),
    path('verify-account/<auth_token>/', views.verify_account, name='verify_account'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    
]

users/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.core.mail import send_mail
from django.contrib.auth.models import AbstractBaseUser, AbstractUser, PermissionsMixin

import uuid

class UserManager(BaseUserManager):
    def create_superuser(self, email, username, password, **extra_fields):
        extra_fields.setdefault('is_verified', True)
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_salesman', True)
        extra_fields.setdefault('is_manager', True)
        extra_fields.setdefault('is_owner', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_active') is not True:
            raise ValueError(_('Superuser must have is_active=True'))
        if extra_fields.get('is_salesman') is not True:
            raise ValueError(_('Superuser must have is_salesman=True'))
        if extra_fields.get('is_manager') is not True:
            raise ValueError(_('Superuser must have is_manager=True'))
        if extra_fields.get('is_manager') is not True:
            raise ValueError(_('Superuser must have is_manager=True'))
        if extra_fields.get('is_owner') is not True:
            raise ValueError(_('Superuser must have is_owner=True'))  

        return self.create_user(email=email, username=username, password=password, **extra_fields) 

    def create_user(self, email, username, password, **extra_fields):
        if not email:
            raise ValueError(_('You must provide an email address')) 

        email = self.normalize_email(email)
        user = self.model(email=email, username=username, **extra_fields)
        user.set_password(password)
        user.save()
        return user



class User(AbstractBaseUser, PermissionsMixin):
    def generate_unique_id():
        try:
            users = User.objects.all()
        except:
            users = False
        
        if users:
            while True:
                id = uuid.uuid4()
                auth_token = User.objects.filter(auth_token=id)
                if not auth_token:
                    break
        else:
            id = uuid.uuid4()

        return id
    email = models.EmailField(_('email address'), unique=True)
    username = models.CharField(max_length=30, unique=True)
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    contact = models.CharField(max_length=11, blank=True)
    location = models.CharField(max_length=100, blank=True)
    bio = models.TextField(max_length=500, blank=True)
    date_joined = models.DateTimeField(default=timezone.now)
    avatar = models.ImageField(upload_to='users/', null=True, blank=True)
    
    auth_token = models.CharField(max_length=100, default=generate_unique_id())
    is_verified = models.BooleanField(default=False)

    is_active = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_salesman = models.BooleanField(default=False)
    is_manager = models.BooleanField(default=False)
    is_owner = models.BooleanField(default=False)
    

    objects = UserManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def __str__(self):
        return self.username

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()


    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)




































# from django.db import models
# from django.contrib.auth.models import User

# import uuid
# # Create your models here.

# class Profile(models.Model):
#     user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)
#     first_name = models.CharField(max_length=50, null=True)
#     last_name = models.CharField(max_length=50, null=True)
#     image = models.ImageField(upload_to='profile_images', default='profile_images/profile_default.jpg')
#     nid    = models.FileField(upload_to='users_nid', blank=True, null=True)
#     phone1 = models.CharField(max_length=11)
#     phone2 = models.CharField(max_length=11, blank=True, null=True)
#     address = models.CharField(max_length=100)
#     auth_token = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
#     is_verified = models.BooleanField(default=False)
#     created = models.DateTimeField(auto_now_add=True)

#     def __str__(self):
#         return str(self.user)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import Group
from django.db import models
from django.db.models.fields import CharField

from users.models import User
class UserCreationForm(UserCreationForm):
    # first_name = forms.CharField(required=True)
    # last_name = forms.CharField(required=True)
    # email = forms.EmailField(required=True)
    
    class Meta:
        model = User
        fields = ['email', 'username', 'password1', 'password2', 
            'is_salesman', 'is_manager', 'is_owner',]

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email', 'username', 'is_salesman', 'is_manager', 'is_owner',]


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = '__all__'

# class ProfileForm(forms.ModelForm):
#     class Meta:
#         models = Profile
#         fields = '__all__'
#         exclude = ['is_verified']

users/views.py
from django.http.response import Http404, HttpResponse
from django.shortcuts import redirect, render
from django.contrib import messages

from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required, user_passes_test

from django.core.mail import send_mail
from django.conf import settings

from users.forms import UserCreationForm, UserUpdateForm
from users.models import User



# Create your views here.
@login_required()
@user_passes_test(lambda u: u.is_active or u.is_manager or u.is_owner or u.is_superuser)
def user(request):
    subject = "Your account needs to be verified"
    message = 'Hello shafayet! '
    # email_from = settings.EMAIL_HOST_USER
    # recipient_list = ['shafayetbs@gmail.com',]

    # send_mail(
    #     subject,
    #     message,
    #     email_from,
    #     recipient_list,
    #     fail_silently=False,
    #     )


    users = User.objects.all()
    context = {
        'title': 'Users',
        'users': users,
    }
    return render(request, 'users/user.html', context)





@login_required()
@user_passes_test(lambda u: u.is_active)
@user_passes_test(lambda u: u.is_active or u.is_manager or u.is_owner or u.is_superuser)
def update_user(request, pk):
    creator = request.user
    user = User.objects.get(id=pk)
    form = UserUpdateForm(instance=user)
    if request.method == 'POST':
        form = UserUpdateForm(request.POST, instance=user)
        if form.is_valid():
            return _extracted_from_update_user(form, creator, request)
        else:
            print(form.errors)
    context = {
        'title': 'Update User',
        'form': form,
    }
    return render(request, 'users/update-user.html', context)
    

def _extracted_from_update_user(form, creator, request):
    username = form.cleaned_data.get('username')
    designation = form.cleaned_data.get('designation')
    # print(creator.groups.get(name='manager').name)

    if str(designation) in ['manager', 'owner']:
        try:
            if str(creator.groups.get(name='manager').name) == 'manager':
                messages.error(request, 'Oops! You do not have permission to update into manager/owner.')
                return redirect('users:user')
        except:
            pass

    form.save()

    user = User.objects.get(username=username)
    user.groups.clear()
    user.groups.add(designation)

    messages.success(request, 'User has been updated')
    return redirect('users:user')



@login_required()
@user_passes_test(lambda u: u.is_active or u.is_manager or u.is_owner or u.is_superuser)
def create_user(request):
    form = UserCreationForm()
    creator = request.user
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            designation = form.cleaned_data.get('designation')
            if str(designation) in ['manager', 'owner']:
                try:
                    if str(creator.groups.get(name='manager').name) == 'manager':
                        messages.error(request, 'Oops! You do not have permission to update into manager/owner.')
                        return redirect('users:user')
                except:
                    pass
            form.save()
            
            user = User.objects.get(username=username)
            user.groups.add(designation)
            messages.success(request, 'An email has been sent to verify this account')
            return redirect('users:user')
    context = {
        'title': 'Create User',
        'form': form
    }

    return render(request, 'users/user-creation-form.html', context)


def verify_account(request, auth_token):
    try:
        user = User.objects.get(auth_token=auth_token)
        
        if user:
            if user.is_verified:
                messages.info(request, 'Your account is already verified')
                return redirect('users:login')

            user.is_verified = True
            user.save()

            messages.success(request, 'Your account has been verified. You can login now.')
            return redirect('users:login')
  
    except:
        return HttpResponse('Something went wrong')


# User authentication for login
def login(request):
    error = False
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        print(username)
        try:
            user = User.objects.get(email=username)
            print(user)
            if user is not None:
                if not user.is_verified:
                    messages.error(request, 'Your account needs to be verified.')
                    return redirect('users:login')
            
                if user.is_verified:
                    user = authenticate(request, username=username, password=password)
                    if user is not None:
                        auth_login(request, user)
                        messages.success(request, f'Hey {username}! You have been logged in.')
                        return redirect('products:dashboard')
                    else:
                        error = True
        except Exception as e:
            messages.error(request, e)
            return redirect('users:login')

    context = {
        'title': 'POS | Login',
        'error': error,
    }
    
    return render(request, 'users/login.html', context)
                 


# This works for logout
def logout(request):
    auth_logout(request)
    messages.success(request, f'Hey! You have been logged out.')
    return redirect('users:login')

users/templates/users/login.html
{% extends 'users/login_base.html' %}
{% load crispy_forms_tags %}
{% block login %}
<div class="card card-outline card-info">
  <div class="card-header text-center">
      <h1><b> {{ site_title }} </b></h1>
  </div>
  <!-- login-card-body -->
  <div class="card-body" style="width: 420px;">
    {% if error %}
    <div class="d-flex justify-content-start p-3 text-danger font-weight-bold border border-radius border-danger mb-4">
      <span >
        Please enter the correct username and password. Note that both fields may be case-sensitive.
      </span>
    </div>
    {% endif %}
   
    <form action="" method="post">
        {% csrf_token %}
      <div class="input-group mb-3">
        <input type="text" class="form-control" placeholder="Username" name="username" value="">
        <div class="input-group-append">
          <div class="input-group-text">
            <span class="fas fa-user"></span>
          </div>
        </div>
      </div>
      <div class="input-group mb-3">
        <input type="password" class="form-control" placeholder="Password" name="password">
        <div class="input-group-append">
          <div class="input-group-text">
            <span class="fas fa-lock"></span>
          </div>
        </div>
      </div>
      <div class="d-flex justify-content-start">
          <button type="submit" class="btn btn-info btn-block">Log In</button>
      </div>
    </form>

    <p class="mb-1 d-inline">
      <a href="{% url 'password_reset' %}">I forgot my password</a>
    </p>
  </div>
  <!-- /.login-card-body -->
</div>
{% endblock login %}
<button type="submit" class="btn btn-info btn-block">Request for new password</button>

users/templates/users/login_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% if title %}
  <title>{{ title }}</title>
  {% else %}
      <title>Pos</title>
  {% endif %}

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.css' %}">
  <!-- icheck bootstrap -->
  <!-- <link rel="stylesheet" href="../../plugins/icheck-bootstrap/icheck-bootstrap.min.css"> -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'css/adminlte.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/sweetalert2.min.css' %}">
  <!-- JQuery -->
  <script src="{% static 'js/jquery.js' %}"></script>
  <!-- This file stays this position otherwise toastr notification won't work-->
  <script src="{% static 'plugins/sweetalert2/sweetalert2.min.js' %}"></script>
  <script src="{% static 'js/toastr_notification.js' %}"></script>
  <style>
      .login-box{
          width: auto;
      }
  </style>
  
</head>
<body class="hold-transition login-page">
    {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'success'%}
                <script type=text/javascript>
                    Toast.fire({
                        icon: '{{ message.tags }}',
                        title: '{{ message }}'
                    })
                </script>
            {% elif message.tags == 'info' %}
                <script type=text/javascript>
                    Toast.fire({
                        icon: '{{ message.tags }}',
                        title: '{{ message }}'
                    })
                </script>
            {% elif message.tags == 'warning' %}
                <script type=text/javascript>
                    Toast.fire({
                        icon: '{{ message.tags }}',
                        title: '{{ message }}'
                    })
                </script>
            {% elif message.tags == 'error' %}
                <script type=text/javascript>
                    Toast.fire({
                        icon: '{{ message.tags }}',
                        title: '{{ message }}'
                    })
                </script>
            {% endif %}
        {% endfor %}
    {% endif %}
    <div class="login-box">
        {% block login %}

        {% endblock login %}
    </div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="{% static 'js/jquery.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

users/templates/users/update-user.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <form action="" method="POST">
        {% csrf_token %}
        <div class="card text-dark text-dark bg-light">
            <h3 class="card-header bg-info">Update User</h3>
            <div class="card-body"">
                <div class="row">
                    <div class="form-group col-sm-6">
                        {{ form.email|as_crispy_field }}
                    </div>
                    <div class="form-group col-sm-6">
                        {{ form.username|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-sm-4">
                        {{ form.is_salesman|as_crispy_field }}
                    </div>
                    {% if user.is_owner or user.is_superuser %}
                    <div class="form-group col-sm-4">
                        {{ form.is_manager|as_crispy_field }}
                    </div>
                    <div class="form-group col-sm-4">
                        {{ form.is_owner|as_crispy_field }}
                    </div>
                    {% endif %}
                </div>
                <button class="btn btn-md btn-info float-right" type="submit">Submit</button>
            </div>
           
        </div>
        
    </form>
</div>
{% endblock %}

users/templates/users/user-creation-form.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <form action="" method="post">
        {% csrf_token %}
        <div class="card text-dark text-dark bg-light">
            <h3 class="card-header bg-info">Create New User</h3>
            <div class="card-body"">
                <div class="row">
                    <div class="form-group col-sm-6">
                        {{ form.email|as_crispy_field }}
                    </div>
                    <div class="form-group col-sm-6">
                        {{ form.username|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-sm-6">
                        {{ form.password1|as_crispy_field }}
                    </div>
                    <div class="form-group col-sm-6">
                        {{ form.password2|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-sm-4">
                        {{ form.is_salesman|as_crispy_field }}
                    </div>
                    {% if user.is_owner and user.is_superuser %}
                    <div class="form-group col-sm-4">
                        {{ form.is_manager|as_crispy_field }}
                    </div>
                    <div class="form-group col-sm-4">
                        {{ form.is_owner|as_crispy_field }}
                    </div>
                    {% endif %}
                </div>
                <button class="btn btn-md btn-info float-right" type="submit">Submit</button>
            </div>
           
        </div>
        
    </form>
</div>
{% endblock %}

users/templates/users/user.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="card">
    <div class="p-4">
        <div class="row">
            <div class="col-sm-6 ">
                <span class="display-4">Users</span>
            </div>
        </div>

        <div class="col d-flex justify-content-end">
            <a class="btn btn-info p-2" href="{% url 'users:create_user' %}">
                <i class="fas fa-plus"></i>
                Create User
            </a>
        </div>
    </div>
    <div class="card-body">
        <table id="datatable" class="table table-striped table-bordered" style="width:100%">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Date Joined</th>
                    <th>Last Login</th>
                    <th>Username</th>
                    <th>User</th>
                    <th>Email</th>
                    <th>Phone</th>
                    <th>Designation</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% if users %}
                    {% for user in users %}
                        <tr>
                            <td> {{user.id}} </td>
                            <td> {{user.date_joined}} </td>
                            <td> {{user.last_login}} </td>
                            <td> {{user.username}} </td>
                            <td> {{user.get_full_name}} </td>
                            <td> {{user.email}} </td>
                            <td> {{user.phone1}} {% if user.profile.phone2 %}, {{user.profile.phone2}} {% endif %}</td>
                            <td> 
                                {% if user.is_owner %}
                                    Owner
                                {% elif user.is_manager %}
                                    Manager
                                {% endif %}
                                
                            </td>
                            {% if user.is_superuser %}
                            <td></td>
                            
                            {% elif request.user == user.is_manager %}
                                <td></td>
                            {% else %}
                            <td>
                                <a href="{% url 'users:update_user' user.id %}">
                                    <i class="fas fa-eye"></i>
                                </a>
                            </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                {% endif %}
            </tbody>
            <tfoot>
                <tr>
                    <th>Id</th>
                    <th>Date Joined</th>
                    <th>Last Login</th>
                    <th>Username</th>
                    <th>User</th>
                    <th>Email</th>
                    <th>Phone</th>
                    <th>Designation</th>
                    <th>Action</th>
                </tr>
            </tfoot>
        </table>
    </div>
</div>
{% endblock %}