expenses/urls.py
from django.urls import path
from expenses import views

app_name = 'expenses'
urlpatterns = [
    path('expense/', views.expense, name='expense'),
    path('add-expense/', views.add_expense, name='add_expense'),
    path('delete-expense/', views.delete_expense, name='delete_expense'),
    path('expense-report/', views.expense_report, name='expense_report'),
]

inventories/urls.py
from django.urls import path
from inventories import views

app_name = 'inventories'
urlpatterns = [
    path('inventory/', views.inventory, name='inventory'),

]

pos/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth.views import (
    PasswordResetView, 
    PasswordResetConfirmView, 
    PasswordResetDoneView, 
    PasswordResetCompleteView
)
from django.contrib import admin

admin.site.site_header = 'XoftNology'                      # default: "Django Administration"
admin.site.index_title = 'XoftNology Dashboard'          # default: "Site administration"
admin.site.site_title = 'Admin' # default: "Django site admin"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='products')),
    path('', include('customers.urls', namespace='customers')),
    path('', include('suppliers.urls', namespace='suppliers')),
    path('', include('sales.urls', namespace='sales')),
    path('', include('inventories.urls', namespace='inventories')),
    path('', include('expenses.urls', namespace='expenses')),
    path('', include('purchases.urls', namespace='purchases')),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('users.urls',  namespace='users')),
    path('', include('app_settings.urls', namespace='app_settings')),

    path('password-reset/', PasswordResetView.as_view(
        template_name='users/password_reset/password_reset.html'), 
        name='password_reset'), 

    path('password_reset/done', PasswordResetDoneView.as_view(
        template_name='users/password_reset/password_reset_done.html'), 
        name='password_reset_done'),  

    path('password_reset_confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset/password_reset_confirm.html'), 
        name='password_reset_confirm'),

    path('password_reset/complete/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset/password_reset_complete.html'),
        name='password_reset_complete'),



]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

products/urls.py
from django.urls import path

from products import views

app_name = 'products'
urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('category/', views.product_category, name='category'),
    path('category-details/<int:pk>', views.category_details, name='category_details'),
    path('create-product-cat', views.create_product_cat, name='create_category'),


    path('product/', views.product, name='product'),
    path('create-product/', views.create_product, name='create_product'),
    path('update-product/<int:pk>/', views.update_product, name='update_product'),
    path('delete-product/', views.delete_product, name='delete_product'),


    path('sales-order/', views.salesOrder, name='sales_order'),
    path('customer-list/', views.customerList, name='customer_list'),
    path('customerProfile/', views.customerProfile, name='customerProfile'),


    path('sales-order/search/', views.search, name='search_product'),
    path('find_product/', views.find_product, name='find_product'),

    path('print-barcode/', views.print_barcode, name='print_barcode'),

]

users/urls.py
from django.urls import path
from users import views

app_name = 'users'
urlpatterns = [
    path('user/', views.user, name='user'),
    path('update-user/<int:pk>/', views.update_user, name='update_user'),
    path('create-user/', views.create_user, name='create_user'),
    path('verify-account/<auth_token>/', views.verify_account, name='verify_account'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if title %}
    <title>{{ title }}</title>
    {% else %}
        <title>Pos</title>
    {% endif %}

    <!-- The following css is for navbar and sidebar starts-->
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- sweetalert2 css -->
    <link rel="stylesheet" href="{% static 'css/sweetalert2.min.css' %}">
    <!-- DataTables -->
    <link rel="stylesheet" href="{% static 'css/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/DateTime-1.0.3/css/dataTables.dateTime.min.css' %}">

    
    <!---- Google FONTS-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;400;700;900&display=swap" rel="stylesheet">
    <!----- FONT AWESOME  -->
    <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/fontawesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.css' %}">

    <link rel="stylesheet" href="{% static 'plugins/jquery-ui/jquery-ui.min.css' %}">
    

    
    
    
    <!------------BaseNav page CSS ------------>
    <!-- <link rel="stylesheet" href="{% static 'css/basenav.css' %}"> -->
    <!-- navbar and sidebar ends-->
    <link rel="stylesheet" href="{% static 'css/vs.css' %}">
    <!------------Sales Order CSS ------------>
    <link rel="stylesheet" href="{% static 'css/sales-order.css' %}">
    <link rel="stylesheet" href="{% static 'css/alt/sales-order-section-grid.css' %}">
    <!------------Reusable CSS ------------>
    <link rel="stylesheet" href="{% static 'css/reusable.css' %}">

    <!-- Necessary File for Navbar and Sidebar -->
    <link rel="stylesheet" href="{% static 'css/sidebar-nav-main.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
    <!-- <link rel="stylesheet" href="{% static 'css/softnology.css' %}"> -->

    <!-- Customer profile css -->
    <link rel="stylesheet" href="{% static 'css/customer-profile.css' %}">
    {% block  internal_css %}{% endblock internal_css %}
    <!-- Css from Shafayet -->
    <!-- Toastr notification -->
    <link rel="stylesheet" href="{% static 'toastr/toastr.min.css' %}">
    <!-- jQuery -->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/select2/css/select2.min.css' %}">
    <!-- JQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>
    <!-- This file stays this position otherwise toastr notification won't work-->
    <script src="{% static 'plugins/sweetalert2/sweetalert2.min.js' %}"></script>
    <script src="{% static 'toastr/toastr.min.js' %}"></script>
    <script src="{% static 'js/toastr_notification.js' %}"></script>
</head>
<body class="hold-transition sidebar-mini layout-fixed">
    <!-- Site wrapper -->
    <div class="wrapper">
        {% if user.is_authenticated %}
            {% include 'navbar.html' %}
            {% include 'sidebar.html' %}
        {% endif %}

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">

            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'success'%}
                        <script type=text/javascript>
                            Toast.fire({
                                icon: '{{ message.tags }}',
                                title: '{{ message }}'
                            })
                        </script>
                    {% elif message.tags == 'info' %}
                        <script type=text/javascript>
                            Toast.fire({
                                icon: '{{ message.tags }}',
                                title: '{{ message }}'
                            })
                        </script>
                    {% elif message.tags == 'warning' %}
                        <script type=text/javascript>
                            Toast.fire({
                                icon: '{{ message.tags }}',
                                title: '{{ message }}'
                            })
                        </script>
                    {% elif message.tags == 'error' %}
                        <script type=text/javascript>
                            Toast.fire({
                                icon: '{{ message.tags }}',
                                title: '{{ message }}'
                            })
                        </script>
                    {% endif %}
                {% endfor %}
            {% endif %}
            
            {% block content %}{% endblock content %}
            
        </div>
        <!-- /.content-wrapper -->





    </div>
    {% if user.is_authenticated %}
    <footer class="main-footer">
        <div class="float-right d-none d-sm-block">
        <b>Version</b> 1.0.0-SH
        </div>
        <strong>Doveloped by XoftNology</strong>
    </footer>
    {% endif %}




    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Bootstrap JS then toastr.js, then toastr notification then others-->
    <!-- <script src="{% static 'js/jquery-3.5.1.js' %}"></script> -->
    
    
    <!-- <script src="{% static 'js/bootstrap.min.js' %}"></script> -->
    <!-- js file for navbar and sidebar are (overlayScrollbars, bundle.min.js, sidebar-nav-main.js) -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
    <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
    <script src="{% static 'js/sidebar-nav-main.js' %}"></script>
    <script src="{% static 'js/jquery-ui.js' %}"></script>

    <!-- Select2 required Js file -->
    <script src="{% static 'plugins/select2/js/select2.min.js' %}"></script>

   

    <!-- DataTables  & Plugins --> <!-- DataTable's necessary JS files -->
    <script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
    <script src="{% static 'plugins/jszip/jszip.min.js' %}"></script>
    <script src="{% static 'plugins/pdfmake/pdfmake.min.js' %}"></script>
    <script src="{% static 'plugins/pdfmake/vfs_fonts.js' %}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>
    <script src="{% static 'plugins/moment/moment.min.js' %}"></script>
    <script src="{% static 'plugins/DateTime-1.0.3/js/dataTables.dateTime.min.js' %}"></script>
     
    {% block datatable_js_script %} {% endblock datatable_js_script %}
    
    {% block sales_history_datatable_js %} {% endblock sales_history_datatable_js %}
    {% block sold_report_datatable_js %} {% endblock sold_report_datatable_js %}
    {% block order_report_datatable_js %} {% endblock order_report_datatable_js %}
    {% block damage_product_report_datatable_js %} {% endblock damage_product_report_datatable_js %}
    {% block return_product_report_datatable_js %} {% endblock return_product_report_datatable_js %}
    {% block expense_report_datatable_js %} {% endblock expense_report_datatable_js %}

    {% block damage_product_datatable_js %} {% endblock damage_product_datatable_js %}
    {% block return_product_datatable_js %} {% endblock return_product_datatable_js %}
    {% block expense_datatable_js %} {% endblock expense_datatable_js %}
    {% block inventory_datatable_js %} {% endblock inventory_datatable_js %}
    {% block purchase_datatable_js %} {% endblock purchase_datatable_js %}
    {% block purchase_report_datatable_js %} {% endblock purchase_report_datatable_js %}
    
    {% block loss_profit_datatable_js %} {% endblock loss_profit_datatable_js %} 
    

    
    
    

    <!-- Custom Select2 -->


    <!-- printThis.js file is for parinting webpage -->
    <script src="{% static 'js/printThis.js' %}"></script>
    <script src="{% static 'js/print-statement.js' %}"></script>
    <!-- JsPdf necessary js File -->
    <script src="{% static 'js/jspdf.min.js' %}"></script>
    {% block scripts_for_jspdf %}{% endblock scripts_for_jspdf %}

    <script src="{% static 'js/jquery-custom-ui.js' %}"></script>

    <script src="{% static 'js/cash_payment.js' %}"></script>
    <script src="{% static 'js/sale-modals.js' %}"></script>
    <script src="{% static 'js/purchase-modals.js' %}"></script>
    <script src="{% static 'js/product-modals.js' %}"></script>
    <script src="{% static 'js/customer-modals.js' %}"></script>
    <script src="{% static 'js/expense-modals.js' %}"></script>
    <script src="{% static 'js/generate-purchase-price.js' %}"></script>
    
    
    {% block search_product %} {% endblock search_product %}
    <!-- {% block add_cart %} {% endblock add_cart %} -->
    <!-- This add_expense.js file lives in 'expenses' app. page-expense.html -->
    {% block add_expense %} {% endblock add_expense %}
    <!-- This add_expense.js file lives in 'purchase' app. page-expense.html -->
    
    <!-- {% block create_product %} {% endblock create_product %} -->
    {% block add_category %} {% endblock add_category %}
    {% block scan_product %} {% endblock scan_product %}

    {% block common_scripts %} {% endblock common_scripts %}
    {% block modal_scripts %}{% endblock modal_scripts %}
    
 
</body>
</html>





 

templates/basenav.html

<header class="header" id="header">
    <div class="header__toggle">
        <i class='fas fa-bars' id="header-toggle"></i>
    </div>
    <!------------Search Bar Top Nav------------>
    <div class="search-bar-top">
        <i class="fas fa-search"></i>
        <form action="">
            <input type="search" placeholder="Search Here...">
        </form>
    </div>
    <!------------Start Top Nav------------>
    <div class="header-part">
        <ul class="noti-nav">
            <!------------Start Notification Area------------>
            <li>
                <a href="#" class="noti__link">
                    <i class='fas fa-bell nav__icon' ></i>
                    <span>15</span>
                </a>   
                
            </li>
            <!------------End Notification Area------------>
            <!------------Start User Image Area------------>
            <li>
                <img src="dist/img/bg.jpg" alt="">
                <div class="user-name">User Name</div>
            </li>
            <!------------End User Image Area------------>
            <!------------Start Dropdown Area------------>
            <li>
                <i  class="fas fa-chevron-down drpbtn dropdown">
                    <div id="profile-menu" class="header-dropdown-content">
                        <a href="#"><i class="fas fa-user-circle"></i>Profile</a>
                        <a href="../../pages/Settings/settings.html"><i class="fas fa-cog"></i>Settings</a>
                        <a href="#"><i class="fas fa-sign-out-alt"></i>Logout</a>
                    </div>                  
                </i>
            </li>
            <!------------EWnd Dropdown Area------------>
        </ul>
    </div>
    <!------------End Top Nav------------>
</header>
<!------------Start Sidbar----------->
<div class="l-navbar" id="nav-bar">
    <nav class="nav">
        <!------------Start Company Logo And Name------------>
        <div class="company-logo">
            <img src="../../dist/img/company-logo.jpg" alt="Company Logo">
        </div>
        <a href="#" class="nav__logo">
            <span class="nav__logo-name">Your Company Name</span>
        </a>
        <!------------End Company Logo And Name------------>
        <!------------Start Sidbar nav list------------>
        <div class="nav__list">
            <a href="{% url 'products:home' %}" class="nav__link {% if request.resolver_match.url_name == 'home' %}active{% endif %}"> 
            <i class='fas fa-th-large nav__icon' ></i>
                <span class="nav__name">Dashboard</span>
            </a>

            <a href="{% url 'products:sales_order' %}" class="nav__link {% if request.resolver_match.url_name == 'sales_order' %}active{% endif %}">
                <i class='fas fa-shopping-basket nav__icon' ></i>
                <span class="nav__name">Sales / Orders</span>
            </a>
            
            <a href="../../pages/ProductCat/product-cat.html" class="nav__link">
                <i class='fas fa-shopping-bag nav__icon' ></i>
                <span class="nav__name">Product</span>
            </a>

            <a href="../../pages/Customer/grid-style-customer.html" class="nav__link">
                <i class='fas fa-users nav__icon' ></i>
                <span class="nav__name">Customer</span>
            </a>

            <a href="{% url 'inventories:inventory' %}" class="nav__link {% if request.resolver_match.url_name == 'inventory' %}active{% endif %}">
                <i class='fas fa-store nav__icon' ></i>
                <span class="nav__name">Inventory</span>
            </a>

            <a href="../../pages/Purchase/Purchase.html" class="nav__link">
                <i class='fas fa-briefcase nav__icon' ></i>
                <span class="nav__name">Purchase</span>
            </a>
            <a href="{% url 'expenses:expense' %}" class="nav__link {% if request.resolver_match.url_name == 'expense' %}active{% endif %}">
                <i class='fas fa-money-bill-wave nav__icon' ></i>
                <span class="nav__name">Expense</span>
            </a>
            <a href="../../pages/Report/report.html" class="nav__link">
                <i class='fas fa-file-medical-alt nav__icon' ></i>
                <span class="nav__name">Report</span>
            </a>
            <a href="../../pages/accounts/accounts.html" class="nav__link">
                <i class='fas fa-calculator nav__icon' ></i>
                <span class="nav__name">Accounts</span>
            </a>
            </div>
                <a href="../../pages/Settings/settings.html" class="nav__link">
                    <i class='fas fa-cog nav__icon' ></i>
                    <span class="nav__name">Settings</span>
                </a>
            </div>
    </nav>
    <!------------End Sidbar nav list------------>
</div>

templates/fixed-sidebar.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>ShoftNogy | POS</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="../../pages/sidebar&navbar/plugins/fontawesome-free/css/all.min.css">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="../../pages/sidebar&navbar/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="../../pages/sidebar&navbar/dist/css/sidebar-nav-main.css">

  <link rel="stylesheet" href="../../pages/sidebar&navbar/dist/css/shoftnogy.css">

</head>
<body class="hold-transition sidebar-mini layout-fixed">
<!-- Site wrapper -->
<div class="wrapper">
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!----Full Button------->
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
      
      
      <!-- User Dropdown -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <div class="user-panel d-flex" >
            <div class="image">
              <img src="../../dist/img/company-logo.jpg" class="img-circle elevation-2" alt="User Image">
            </div>
          </div>
        </a>
        <div class="dropdown-menu dropdown-menu-md dropdown-menu-right">
          <a href="#" class="dropdown-item">
            <i class="fas fa-user-circle mr-2"></i>
            Profile
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-cog mr-2"></i> Settings
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item  text-center">
            <i class="fas fa-sign-out-alt"></i> Logout
          </a>
        </div>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="#" class="brand-link">
      <img src="../../dist/img/company-logo.jpg" alt="ShoftNogy" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-bold text-wrap">ShoftNogy | POS  </span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p> Dashboard </p>
            </a>
          </li>

          <li class="nav-item menu-open">
            <a href="#" class="nav-link active">
              <i class="nav-icon fas fa-copy"></i>
              <p>
                Layout Options
                <i class="fas fa-angle-left right"></i>
                <span class="badge badge-info right">6</span>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="../layout/top-nav.html" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Top Navigation</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="../layout/top-nav-sidebar.html" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Top Navigation + Sidebar</p>
                </a>
              </li>
            </ul>
          </li>
          
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-shopping-basket"></i>
              <p> Sales & Orders </p>
            </a>
          </li>

          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-shopping-bag"></i>
              <p> Product </p>
            </a>
          </li>

          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-users"></i>
              <p> Customer </p>
            </a>
          </li>

          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-store"></i>
              <p> Inventory </p>
            </a>
          </li>

          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-briefcase"></i>
              <p> Purchase </p>
            </a>
          </li>

          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-money-bill-wave"></i>
              <p> Expense </p>
            </a>
          </li>

          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-file-medical-alt"></i>
              <p> Report </p>
            </a>
          </li>

          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-calculator"></i>
              <p> Accounts </p>
            </a>
          </li>

          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-cog"></i>
              <p> Settings </p>
            </a>
          </li>
          
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    

    
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <footer class="main-footer">
    <div class="float-right d-none d-sm-block">
      <b>Version</b> 1.0.0-SH
    </div>
    <strong>Doveloped by ShoftNogy</strong>
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="../../pages/sidebar&navbar/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="../../pages/sidebar&navbar/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- overlayScrollbars -->
<script src="../../pages/sidebar&navbar/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
<!-- AdminLTE App -->
<script src="../../pages/sidebar&navbar/dist/js/sidebar-nav-main.js"></script>

</body>
</html>

templates/navbar.html
{% load static %}
<!-- Navbar -->
<nav class="main-header navbar navbar-expand bg-pos-color">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
    <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
    </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
    <!----Full Button------->
    <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
        <i class="fas fa-expand-arrows-alt"></i>
        </a>
    </li>        
    <!-- User Dropdown -->
    <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
        <div class="user-panel d-flex" >
            {% if not user.profile.image %}
                {{ user.username|title }}
            {% else %}
                <!-- <div class="image">
                    <img src="" class="img-circle elevation-2" alt="User Image">
                </div> -->
                <div >
                    <img src="{{ user.profile.image.url }}"  alt="Customer Image" class="rounded-circle" style="height: 25px; width: 25px;">
                </div>
                <span class="mt-1">{{ user.username }}</span>
            {% endif %}

        </div>
        </a>
        <div class="dropdown-menu dropdown-menu-md dropdown-menu-right">
        <a href="#" class="dropdown-item">
            <i class="fas fa-user-circle mr-2"></i>
            Profile
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
            <i class="fas fa-cog mr-2"></i> Settings
        </a>
        <div class="dropdown-divider"></div>
        <a href="{% url 'users:logout' %}" class="dropdown-item  text-center">
            <i class="fas fa-sign-out-alt"></i> Logout
        </a>
        </div>
    </li>
    </ul>
</nav>
  <!-- /.navbar -->